---
title: "NEXTSNAKES SUMMARY REPORT"
date: "`r Sys.Date()`"
author: "`r Sys.getenv('LOGNAME')`"
output:
  rmdformats::readthedown:
    code_folding: show
    self_contained: true
    thumbnails: false
    lightbox: false
pkgdown:
  as_is: true
params:
  root: ''
  outdir: ''
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = params$root)
```


# Differnetial Transcript Usage {.tabset}## DRIMSEQ  {.tabset}### COMBINATION  {.tabset}#### 1-vs-2  {.tabset}##### OVERVIEW##### FIGURES##### TABLES  {.tabset}###### genes
            ```{r, table:DTU_DRIMSEQ_COMBINATION_1-vs-2_table_genes.tsv.gz, include = TRUE, echo = FALSE, message = TRUE, warning = FALSE}
            library(DT)
            table <- read.table(gzfile('DTU_DRIMSEQ_COMBINATION_1-vs-2_table_genes.tsv.gz'), header = TRUE)
            DT::datatable(table)
            ```
            ###### genewise-precision
            ```{r, table:DTU_DRIMSEQ_COMBINATION_1-vs-2_table_genewise-precision.tsv.gz, include = TRUE, echo = FALSE, message = TRUE, warning = FALSE}
            library(DT)
            table <- read.table(gzfile('DTU_DRIMSEQ_COMBINATION_1-vs-2_table_genewise-precision.tsv.gz'), header = TRUE)
            DT::datatable(table)
            ```
            

