```{r header, include=FALSE}
author    <- Sys.getenv("LOGNAME")
pres_date <- Sys.Date()
```

---
title:  "POSTPROCESSING SUMMARY"
author: `r author`
date:   `r pres_date`
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# args <- commandArgs(trailingOnly = TRUE)
# input     <- args[1]
# formats   <- args[2]
# outdir    <- args[3]
# cutoffs    <- args[4]

input     <- "DTU/DRIMSEQ/SigUP_DTU_DRIMSEQ_1_vs_2_results_genes.tsv.gz DTU/DRIMSEQ/SigDOWN_DTU_DRIMSEQ_1_vs_2_results_genes.tsv.gz DTU/DRIMSEQ/Sig_DTU_DRIMSEQ_1_vs_2_results_genes.tsv.gz"
outdir    <- "REPORTS"

setwd("PROJECTS/DTU_dev")

analyses <- strsplit(input,'+', fixed=TRUE)[[1]]
works <- unique(sub("\\/.*", '', analyses))

```

***
# OVERVIEW
input: `r input`\
formats: `r formats`\
cutoffs: `r cutoffs`


```{r DE, echo=FALSE, results='asis', eval='DE' %in% works}
cat("
***
# DIFFERENTIAL GENE EXPRESSION
")
```

```{r DE_EDGER, echo=FALSE, results='asis', eval='DE/EDGER' %in% analyses}
cat("
## edgeR
results of DE EDGER analysis: \n
............\n
")

```

```{r DTU, echo=FALSE, results='asis', eval='DTU' %in% works}
cat("
***
# DIFFERENTIAL TRANSCRIPT USAGE
")
```

```{r DTU_DRIMSEQ, echo=FALSE, results='asis', eval='DTU/DRIMSEQ' %in% analyses}
cat("
## DRIMSeq
results of DTU DRIMSeq analysis:\n
............\n
")
list.files('DTU/DRIMSEQ')

```

```{r DTU_DEXSEQ, echo=FALSE, results='asis', eval='DTU/DEXSEQ' %in% analyses}
cat("
## DEXSeq

results of DTU DEXSeq analysis:\n
............\n
")
setwd('DTU/DEXSEQ')
list.files()
```
