name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.10.2
  - grep=3.4
  - picard=2.27.4
  - pyfaidx=0.5.9
  - pysam=0.16.0.1
  - samtools=1.7
  - snakemake-minimal=7.14.2
  - natsort=8.1.0
  - perl=5.26.2
  - pigz=2.6
