name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.15.1
  - grep=3.4
  - picard=2.27.4
  - pyfaidx=0.7.1
  - pysam=0.19.1
  - samtools=1.9
  - snakemake-minimal=7.14.2
  - natsort=8.2.0
  - pandas=1.5.0
  - pandoc=2.19.2
  - perl=5.26.2
  - pigz=2.6
