name: snakemake
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bcftools=1.9
  - grep=2.14
  - picard=2.18.12
  - pyfaidx=0.5.4.1
  - pysam=0.15.0.1
  - samtools=1.9
  - snakemake-minimal=7.14.0
  - natsort=5.4.0
  - pandas=0.23.4
  - pandoc=2.2.2
  - perl=5.26.2
  - pigz=2.4
