__default__:
    account: ${USER} # your account name
    partition: c # the partition to use
    time: 1500 # default time (minutes)
    nodes: 1
    output: "/SLURMLOG/{rule}.{wildcards}.out"
    error: "/SLURMLOG/{rule}.{wildcards}.err"
    #ntasks: 1
    #mem: 14GB # default memory

generate_index:
    mem: 200GB

mapping:
    mem: 200GB

generate_ctat_lib:
    mem: 200GB
    time: 2880

starfusion:
    mem: 100GB
    time: 1500

multiqc:
   mem: 30GB
