executor: slurm

default-resources:
  slurm_account: "${SLURM_ACCOUNT}" # your account name
  slurm_partition: "${SLURM_PARTITION}" # the partition to use
  nodes: 1
  mem_mb: "20000 * (2 ** (attempt - 1))"  
  runtime: "480 * (2 ** (attempt - 1))"   
set-resources:
  generate_index:
    mem_mb: "80000 * (2 ** (attempt - 1))"
  mapping:
    mem_mb: "80000 * (2 ** (attempt - 1))"
  multiqc:
    mem_mb: "40000 * (2 ** (attempt - 1))"
  run_deseq2:
    mem_mb: "40000 * (2 ** (attempt - 1))"
    slurm_qos: "medium"
    runtime: "18h"
  run_DTU:
    mem_mb: "40000 * (2 ** (attempt - 1))"
    slurm_qos: "long"
    runtime: "120h"
  run_edger:
    mem_mb: "40000 * (2 ** (attempt - 1))"
    slurm_qos: "medium"
    runtime: "18h"
  salmon_index:
    mem_mb: "40000 * (2 ** (attempt - 1))"
  sortsam:
    mem_mb: "16000 * (2 ** (attempt - 1))"
    slurm_qos: "rapid"
    runtime: "1h"
  atacorrect:
    mem_mb: "40000 * (2 ** (attempt - 1))"
  bindetect:
    mem_mb: "60000 * (2 ** (attempt - 1))"
  gridss_call:
    mem_mb: "40000 * (2 ** (attempt - 1))"
    threads: 8
  gridss_setupreference:
    mem_mb: "40000 * (2 ** (attempt - 1))"
    threads: 8
jobs: 1000
keep-going: True
rerun-incomplete: True
scheduler: greedy
max-jobs-per-second: 10
max-status-checks-per-second: 10
restart-times: 1
local-cores: 1
latency-wait: 600
